=== 117HD/RLHD/schemas/water_types.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "water_types.schema.json",
  "title": "Water Types",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string",
        "description": "Identifier used to refer to the water type."
      },
      "description": {
        "type": "string",
        "description": "Optional description of what this applies to or is used for."
      },
      "vanillaTextureIndex": {
        "type": "integer",
        "description": "Defines a fallback water type for a specific vanilla texture."
      },
      "flat": {
        "type": "boolean",
        "description": "Whether the water type should be opaque, i.e. not show any underwater geometry."
      },
      "specularStrength": {
        "type": "number",
        "description": "The strength of specular reflections on the water surface."
      },
      "specularGloss": {
        "type": "number",
        "description": "The gloss of specular reflections on the water surface."
      },
      "normalStrength": {
        "type": "number",
        "description": "How intensely the normal maps should affect the water surface."
      },
      "baseOpacity": {
        "type": "number",
        "description": "Roughly how transparent the water should be."
      },
      "fresnelAmount": {
        "type": "number",
        "description": "Mix from 0 to 1 between the specified `surfaceColor` and the sky in the reflection."
      },
      "normalMap": {
        "type": "string",
        "description": "Which normal map to use for the water surface.",
        "enum": [
          "WATER_NORMAL_MAP_1",
          "WATER_NORMAL_MAP_2"
        ]
      },
      "surfaceColor": {
        "type": [ "string", "array" ],
        "description": "The color used for the water surface when `fresnelAmount` is low, specified as a hex color code or an array in the range 0-255, in sRGB. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "foamColor": {
        "type": [ "string", "array" ],
        "description": "The color used for the foam along the shoreline, specified as a hex color code or an array in the range 0-255, in sRGB. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "depthColor": {
        "type": [ "string", "array" ],
        "description": "The color used for the underwater color gradient, specified as a hex color code or an array in the range 0-255, in sRGB. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "hasFoam": {
        "type": "boolean",
        "description": "Whether shoreline foam should be drawn for the water type."
      },
      "duration": {
        "type": "number",
        "description": "The duration before the UV scrolling repeats. Smaller numbers yield faster scrolling waves."
      },
      "fishingSpotRecolor": {
        "type": "integer",
        "description": "A Jagex HSL value to apply to fishing spot replacement models on this water type."
      }
    }
  }
}

=== 117HD/RLHD/src/main/resources/rs117/hd/scene/water_types.json
[
  {
    "name": "WATER_FLAT",
    "surfaceColor": "#69809C",
    "fresnelAmount": 0.85,
    "flat": true
  },
  {
    "name": "SWAMP_WATER",
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.3,
    "surfaceColor": "#172114",
    "foamColor": "#737865",
    "depthColor": "#29521a",
    "duration": 1.2,
    "fishingSpotRecolor": 23454
  },
  {
    "name": "MLM_WATER",
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.3,
    "surfaceColor": [
      30.48,
      41.32,
      74.4
    ],
    "duration": 1.2
  },
  {
    "name": "SWAMP_WATER_FLAT",
    "flat": true,
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.3,
    "surfaceColor": "#172114",
    "foamColor": "#737865",
    "depthColor": "#29521a",
    "duration": 1.2,
    "fishingSpotRecolor": 23454
  },
  {
    "name": "POISON_WASTE",
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.9,
    "fresnelAmount": 0.3,
    "surfaceColor": "#16170d",
    "foamColor": "#6a6c64",
    "depthColor": "#32342e",
    "duration": 1.6
  },
  {
    "name": "BLACK_TAR_FLAT",
    "flat": true,
    "specularStrength": 0.045,
    "specularGloss": 250,
    "normalStrength": 0.075,
    "baseOpacity": 0.9,
    "fresnelAmount": 0.02,
    "surfaceColor": [
      4.94,
      5.41,
      6.16
    ],
    "foamColor": "#000000",
    "depthColor": [
      4.94,
      5.41,
      6.16
    ],
    "duration": 4
  },
  {
    "name": "BLOOD",
    "normalStrength": 0.05,
    "baseOpacity": 0.85,
    "fresnelAmount": 0.0,
    "surfaceColor": "#260000",
    "foamColor": "#753f2d",
    "depthColor": "#321a16",
    "duration": 2.0
  },
  {
    "name": "BLOOD_FLAT",
    "normalStrength": 0.05,
    "baseOpacity": 0.85,
    "fresnelAmount": 0.0,
    "surfaceColor": "#260000",
    "hasFoam": false,
    "depthColor": "#321a16",
    "duration": 2.0,
    "flat": true
  },
  {
    "name": "ICE",
    "specularStrength": 0.3,
    "specularGloss": 200.0,
    "normalStrength": 0.04,
    "baseOpacity": 0.85,
    "normalMap": "WATER_NORMAL_MAP_2",
    "foamColor": "#969696",
    "duration": 0.0
  },
  {
    "name": "ICE_FLAT",
    "flat": true,
    "specularStrength": 0.3,
    "specularGloss": 200.0,
    "normalStrength": 0.04,
    "baseOpacity": 0.85,
    "normalMap": "WATER_NORMAL_MAP_2",
    "foamColor": "#969696",
    "duration": 0.0
  },
  {
    "name": "MUDDY_WATER",
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.7,
    "fresnelAmount": 0.3,
    "surfaceColor": "#230a00",
    "foamColor": "#6a6c18",
    "depthColor": "#411700",
    "duration": 2.7
  },
  {
    "name": "SCAR_SLUDGE",
    "specularStrength": 0.2,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.95,
    "fresnelAmount": 0.03,
    "surfaceColor": "#242824",
    "foamColor": "#21231F",
    "duration": 2
  },
  {
    "name": "ABYSS_BILE",
    "specularStrength": 0.15,
    "specularGloss": 60,
    "normalStrength": 0.08,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.3,
    "surfaceColor": [
      47.89,
      30.68,
      7.5
    ],
    "foamColor": [
      47.89,
      20.98,
      0.0
    ],
    "depthColor": [
      47.89,
      11.15,
      0.0
    ],
    "duration": 3.5
  },
  {
    "name": "PLAIN_WATER",
    "flat": true,
    "foamColor": [
      13.07,
      13.07,
      13.07
    ],
    "depthColor": "#000000"
  },
  {
    "name": "WHISPERER_WATER",
    "flat": true,
    "surfaceColor": "#181823",
    "foamColor": [
      13.07,
      13.07,
      13.07
    ],
    "depthColor": "#0A0A0F"
  },
  {
    "name": "DARK_BLUE_WATER",
    "flat": true,
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.1,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.2,
    "surfaceColor": [
      0.54,
      5.65,
      7.25
    ],
    "foamColor": [
      13.07,
      13.07,
      13.07
    ],
    "depthColor": "#000000"
  },
  {
    "name": "LIGHT_BLUE_WATER",
    "flat": true,
    "specularStrength": 0.1,
    "specularGloss": 400.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.7,
    "fresnelAmount": 0.3,
    "surfaceColor": [
      90,
      110.65,
      100
    ],
    "foamColor": [
      13.07,
      13.07,
      13.07
    ],
    "depthColor": "#000000"
  },
  {
    "name": "ARAXXOR_WASTE",
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.9,
    "fresnelAmount": 0.3,
    "surfaceColor": "#16ff0d",
    "foamColor": "#14ff14",
    "depthColor": "#1eff1a",
    "duration": 1.6
  },
  {
    "name": "CYAN_WATER"
  },
  {
    "name": "GREEN_CAVE_WATER",
    "flat": true,
    "specularStrength": 0.1,
    "specularGloss": 100.0,
    "normalStrength": 0.05,
    "baseOpacity": 0.8,
    "fresnelAmount": 0.3,
    "surfaceColor": "#172114",
    "foamColor": "#737865",
    "depthColor": "#29521a",
    "duration": 1.2,
    "fishingSpotRecolor": 23454
  },
  {
    "name": "CAVE_WATER",
    "specularStrength": 0.2,
    "specularGloss": 100.0,
    "normalStrength": 0.3,
    "baseOpacity": 0.75,
    "fresnelAmount": 0.1,
    "surfaceColor": [
      5.17,
      13.07,
      16.99
    ],
    "foamColor": [
      0.77,
      0.77,
      0.77
    ],
    "depthColor": [
      10.79,
      36.75,
      41.32
    ]
  },
  {
    "name": "CAVE_WATER_MURKY",
    "specularStrength": 0.1,
    "specularGloss": 75.0,
    "normalStrength": 0.3,
    "baseOpacity": 0.86,
    "fresnelAmount": 0.1,
    "surfaceColor": [
      5.17,
      13.07,
      16.99
    ],
    "foamColor": [
      85,
      85,
      85
    ],
    "depthColor": [
      10.79,
      36.75,
      41.32
    ]
  },
  {
    "name": "WATER",
    "surfaceColor": "#69809C",
    "fresnelAmount": 0.85,
    "depth": 200
  },
  {
    "name": "WATER_OPEN",
    "vanillaTextureIndex": 130,
    "surfaceColor": "#556F8F",
    "fresnelAmount": 0.85,
    "depth": 240
  },
  {
    "name": "WATER_SHELF",
    "vanillaTextureIndex": 131,
    "surfaceColor": "#536B88",
    "fresnelAmount": 0.85,
    "depth": 300
  },
  {
    "name": "WATER_DROPOFF",
    "vanillaTextureIndex": 132,
    "surfaceColor": "#4D5D81",
    "fresnelAmount": 0.85,
    "depth": 360
  },
  {
    "name": "WATER_DEEP",
    "vanillaTextureIndex": 133,
    "surfaceColor": "#3C4B71",
    "fresnelAmount": 0.85,
    "depth": 800
  },
  {
    "name": "WATER_TRENCH",
    "vanillaTextureIndex": 134,
    "surfaceColor": "#374467",
    "fresnelAmount": 0.85,
    "depth": 2000
  },
  {
    "name": "WATER_STORMY",
    "vanillaTextureIndex": 135,
    "surfaceColor": "#688B9C",
    "fresnelAmount": 0.85,
    "depth": 200
  },
  {
    "name": "WATER_STORMY_OPEN",
    "vanillaTextureIndex": 136,
    "surfaceColor": "#638189",
    "fresnelAmount": 0.85,
    "depth": 240
  },
  {
    "name": "WATER_STORMY_SHELF",
    "vanillaTextureIndex": 137,
    "surfaceColor": "#537783",
    "fresnelAmount": 0.85,
    "depth": 300
  },
  {
    "name": "WATER_STORMY_DROPOFF",
    "vanillaTextureIndex": 138,
    "surfaceColor": "#55707F",
    "fresnelAmount": 0.85,
    "depth": 360
  },
  {
    "name": "WATER_STORMY_DEEP",
    "vanillaTextureIndex": 139,
    "surfaceColor": "#445C72",
    "fresnelAmount": 0.85,
    "depth": 800
  },
  {
    "name": "WATER_SUNBAKED",
    "vanillaTextureIndex": 140,
    "surfaceColor": "#4D6B7F",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SUNBAKED_OPEN",
    "vanillaTextureIndex": 141,
    "surfaceColor": "#4A6578",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SUNBAKED_SHELF",
    "vanillaTextureIndex": 142,
    "surfaceColor": "#446175",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SUNBAKED_DROPOFF",
    "vanillaTextureIndex": 143,
    "surfaceColor": "#425B71",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SUNBAKED_DEEP",
    "vanillaTextureIndex": 144,
    "surfaceColor": "#3F586C",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_PROFANE",
    "vanillaTextureIndex": 145,
    "surfaceColor": "#6C78A2",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_PROFANE_OPEN",
    "vanillaTextureIndex": 146,
    "surfaceColor": "#606B99",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_PROFANE_SHELF",
    "vanillaTextureIndex": 147,
    "surfaceColor": "#585E8F",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_PROFANE_DROPOFF",
    "vanillaTextureIndex": 148,
    "surfaceColor": "#473D72",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_PROFANE_DEEP",
    "vanillaTextureIndex": 149,
    "surfaceColor": "#3F3863",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_CURSED",
    "vanillaTextureIndex": 150,
    "surfaceColor": "#68799D",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_CURSED_OPEN",
    "vanillaTextureIndex": 151,
    "surfaceColor": "#606E90",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_CURSED_SHELF",
    "vanillaTextureIndex": 152,
    "surfaceColor": "#536489",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_CURSED_DROPOFF",
    "vanillaTextureIndex": 153,
    "surfaceColor": "#4F5781",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_CURSED_DEEP",
    "vanillaTextureIndex": 154,
    "surfaceColor": "#3F4672",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SCALDING",
    "vanillaTextureIndex": 155,
    "surfaceColor": "#6E7595",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SCALDING_OPEN",
    "vanillaTextureIndex": 156,
    "surfaceColor": "#656B88",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SCALDING_SHELF",
    "vanillaTextureIndex": 157,
    "surfaceColor": "#596181",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SCALDING_DROPOFF",
    "vanillaTextureIndex": 158,
    "surfaceColor": "#585874",
    "fresnelAmount": 0.85
  },
  {
    "name": "WATER_SCALDING_DEEP",
